language: java
jdk:
  - oraclejdk7

env:
  global:
    # PASSWORD=pwd
    secure: "RwQ1Fxe/O4PxdvsJjiPFoAUuX/pqNLAxAr5dBCK7cx+DpXtnYMAk2MRgdr2ih03B+tU55LzZKi1BCzALlt9v/77FpO4foz2c5/WPlK9my7Xic+U+1aoiG9FEFR9loLu/3S/mNfEXc/nwgu/dtttwYb2enApri65PUMaIoui3SLQ="

script: mvn deploy

after_success:
  - chmod +x deploy.sh
  - ./deploy.sh

