language: java
jdk:
  - oraclejdk7

env:
  global:
    # PASSWORD=pwd
    secure: "KIOM1785IynPBAwPvC0Qn/KX9F17hupjZLTGiC/cMH433cQpsmBl1fFSmKdUMCCe5X4mimi/ZcZwVSb4Kg/oGKs57w7oOKthV7fTU5gtSOWnAa9ks0KGx27uuddPyo3TF4BQMlaABOPylAdFIobVdTRjng4a0drAJK2kxQxpeUo="

script: mvn deploy

after_success:
  - chmod +x deploy.sh
  - ./deploy.sh

